@id=1be6aa47-61c4-4bb5-af47-7205349150b1
PUT http://localhost:5204/product/{{id}}
Content-Type : application/json

{
    "name": "Zapatillas de Kill 21222",
    "description": "Product 200 description",
    "startDateTime": "2019-01-01T00:00:00.000Z",
    "endDateTime": "2019-01-01T00:00:00.000Z",
    "color": [
        "red",
        "green",
        "blue"
    ],
    "size": [
        "small",
        "medium"    ]
}
